### ISSUE TITLE
Does go-chromecast works on Macos?

### ISSUE THREAD

**Issue by pr4bh4sh** [vishen/go-chromecast#137]
I installed it as below but I can't seem to make it work
```
$ go get -u github.com/vishen/go-chromecast
$ go-chromecast ui
zsh: command not found: go-chromecast
```
macos version: 12.3 (21E230)
I don't have any experience with using go or tools written in go. Am I missing something?

**Comment by vishen** [comment]
@pr4bh4sh Apologies, those instructions may be not up-to-date with Go 1.18 now. `go-chromecast` should work on a mac, are you able to try installing with `go install github.com/vishen/go-chromecast@latest`?

**Comment by vishen** [comment]
Ah sorry, I misread your original post. I think the Go bin directory isn't added to your path so it can't find the install `go-chromecast`.

It will be different depending on how you installed Go, but if you run:

```
$  go env | grep -i gopath
GOPATH="/Users/vishen/go"
$ ls /Users/vishen/go/bin
... 
go-chromecast 
...

$ /Users/vishen/go/bin/go-chromecast --version
go-chromecast dev (master) 2022-05-25T21:25:17Z
```

If that works then you can add the bin directory to your path. Let me know if the above helps at all, otherwise if you could paste your `go env` output I can try and help out :)

**Comment by pr4bh4sh** [comment]
It works after adding the go path to $PATH. Thank you so much for helping me and for creating this tool.
