### ISSUE TITLE
Load and play media from start time

### ISSUE THREAD

**Issue by exsqzme** [vishen/go-chromecast#145]
Is there a way to pass a starting position flag to the load command to have the media start at a certain position?

**Comment by vishen** [comment]
It should be possible with a small change to the API. The start time is set https://github.com/vishen/go-chromecast/blob/master/application/application.go#L760, so we could pass the start time through from https://github.com/vishen/go-chromecast/blob/master/cmd/load.go#L67 to https://github.com/vishen/go-chromecast/blob/master/application/application.go#L720 and add a new cli argument for the start time.

I am currently away and I don't have a chromecast to test this on. Feel free to send a PR, otherwise I can take a look when I get back home with a chromecast.

**Comment by exsqzme** [comment]
OK, I will take a look at implementing this. Thanks!
