### ISSUE TITLE
Non-interactive mode

### ISSUE THREAD

**Issue by Rapti** [vishen/go-chromecast#159]
From what I can tell, `go-chromecast` lacks a non-interactive mode, which makes it difficult to use in other scripts.
For example, if I specify a device using `-u <uuid>` and that device can't be found, I'm prompted to select one of the other devices on the network. Similarly, if a watched device goes offline, `go-chromecast` returns to the select prompt instead of exiting. The `--first` flag also doesn't accomplish this; if I pass it and the device goes offline, `go-chromecast` starts to watch a random other device it can find (which I would consider a bug on its own).

I'd very much appreciate a command line flag that causes `go-chromecast` to exit with an error code in such cases instead of waiting for user input.

**Comment by vishen** [comment]
That seems reasonable, the fact that `--first` behaves that way isn't good. Fixing `--first` and adding `--non-interactive` flag that disables prompts seems like a good idea.

> Similarly, if a watched device goes offline, go-chromecast returns to the select prompt instead of exiting
This is surprising to me, and seems like a bug. `go-chromecast` should exit if the device can't be found after a number of reconnects. I don't have a chromecast currently to test this on, are you able to provide some debug and verbose logging of this happening?

**Comment by vishen** [comment]
I think I see the issues; one is a bug and other was poor api design that causes some ambiguity. I have updated `master` with the following fixes;

1. If a device filter is supplied but no device is found ,then return an error
2. If a device filter is supplied and '--first' is supplied, then only return the device that matches the filter (rather than the first).

@Rapti Let me know if that fixes the issues at all.

**Comment by Rapti** [comment]
Thanks for the quick fix! It works as expected and doesn't even require a change in `sponsorblockcast`, which is why I came here in the first place.
