### ISSUE TITLE
Watch command does not receive any events

### ISSUE THREAD

**Issue by MeanderingCode** [vishen/go-chromecast#21]
I am neither familiar with golang nor chromecast network protocols, so please pardon my ignorance in discussing this issue.

When I launch the `watch` command, I receive one status output and never anything further. I have used my Google Home via Spotify and voice commands, as well as using `go-chromecast` to `load`, run `ui`, and get `status`.

My assumption is that I would receive some other messages over time, though I am not clear on what events would be received by this listener.

**Comment by vishen** [comment]
Your assumption is correct; you should see any media update events that occur, such as, a song changing on Spotify, etc. 

Does this happen every time you run `go-chromecast watch`? What happens if you run `go-chromecast load --debug <file_or_url>`, do you receive any events then?

I am currently in the middle of moving, so I don't have a chromecast or home mini set up unfortunately. But I will take a look in a week or so!

**Comment by MeanderingCode** [comment]
Thank you for the response.

It has happened every time. I will test the use of debug when I can.

To confirm, this should also show events from a Spotify instance on the network sending commands, or voice control e.g. playing music from Spotify?

**Comment by MeanderingCode** [comment]
Additional information:
`go-chromecast` compiled with `go get` at `master` commit `aa12db5485826422c020e57842846997f8c86e4e`
Debian Stretch "Raspbian" kernel `4.14.79` arch `armv6l` on RaspberryPi 2 B+

**Comment by vishen** [comment]
> To confirm, this should also show events from a Spotify instance on the network sending commands, or voice control e.g. playing music from Spotify?

It should be the updates that the chromecast broadcasts for certain events, I am not 100% on all the events, but I have seen it broadcast events for going to the next song or video, or occasionally it will broadcast just general status updates. 

You should be seeing at least somethings because the chromecast is supposed to broadcast updates, there is likely a bug in the code so I will have to track it down :)

**Comment by MeanderingCode** [comment]
I just realized that it isn't clear that this is a Google Home device I am interacting with.
Perhaps there is a difference in the device where it does not broadcast in the same way, but this would surprise me a little because the API is the same (hence this tool working) and I expect the devices to keep coordinated with each other through network broadcasts.

**Comment by vishen** [comment]
> I just realized that it isn't clear that this is a Google Home device I am interacting with.

Ah, I don't think I tested with a Google Home device, only my Chromecast device. I'll test out with both when I get a chance. But I agree, I would presume they would both behave the same way.

**Comment by vishen** [comment]
This appears to be an issue from when we moved to `logrus`. This should be fixed now in the latest release `0.0.7`,
