### ISSUE TITLE
Never exits after loading internet hosted file

### ISSUE THREAD

**Issue by jmbromley** [vishen/go-chromecast#36]
When loading an internet hosted file from the CLI, the command never exits even after playing has finished.  The intuitive behaviour is that the command should exit when playing is complete.

Since no local server need be set up when playing an internet hosted file it would perhaps be even better to exit straightaway as soon as the chromecast device has accepted the file for playing (or perhaps make this behaviour optional e.g. with a "--detach" option).

Use case:  I'm trying to script a jukebox like application that accepts URLs for files to play from a web frontend, and I'd really prefer not to have lots of stale processes hanging around (particularly if they are internally still running an event loop...)

**Comment by vishen** [comment]
Ah, this is an oversight sorry! We could do either option; exit straight away, or exit after the video has finished playing (since we get the media finished notification). I think the latter would be more consistent with how the loading of local files works, but it also doesn't make sense to me in this case. I think it should exit straight away, unless the `--with-ui` flag is passed through.
