### ISSUE TITLE
Add a fast way to select first chromecast device

### ISSUE THREAD

**Issue by oliverpool** [vishen/go-chromecast#58]
_I also have a chromecast library (https://github.com/oliverpool/go-chromecast/) which works well, but lacks some of the nice features of your project (the ui for instance)._

However in my case (I only have one chromecast) my library is **faster to start**: instead of scanning for a couple of seconds and returning a list of devices, it scans until it finds the device matching the description (with a given name or uuid for instance) and returns immediately.

On my network I have the following results:
- my library: `./chromecast status  0.00s user 0.01s system 22% cpu 0.073 total`
- this project: `./go-chromecast status  0.01s user 0.02s system 0% cpu 3.066 total`
The  **total**  is less than on tenth of a second instead of 3 :-)

I propose to add a `--first` flag and implement the same behavior to this library: scan until the first matching device is found (I would even prefer not having a flag, but this would be a breaking change).

If you think that this could be a good idea, I could try to craft a PR.
I will likely take inspiration from my library (https://github.com/oliverpool/go-chromecast/tree/master/discovery - it actually supports 2 scanners: https://github.com/hashicorp/mdns & https://github.com/grandcat/zeroconf - `discovery` containing the common code)

**Comment by oliverpool** [comment]
I would also recommend switching from https://github.com/hashicorp/mdns to https://github.com/grandcat/zeroconf (it has a nicer interface and no annoying logs)

**Comment by vishen** [comment]
Hello @oliverpool ! Yes, this does seem like an issue; I guess it is because of https://github.com/vishen/go-chromecast/blob/master/dns/dns.go#L76 which waits 3 seconds for dns responses to return.

I am happy with your approach of adding a `--first` flag. If you think your approach is cleaner or better than what is currently there feel free to make an MR :) 

> I would also recommend switching from https://github.com/hashicorp/mdns to https://github.com/grandcat/zeroconf (it has a nicer interface and no annoying logs)

I have been considering this actually but haven't gotten around to it. I am happy to remove `mdns` for `zeroconf` if they work similarly.
