### ISSUE TITLE
error while installing with "go get"

### ISSUE THREAD

**Issue by Bluscream** [vishen/go-chromecast#73]
![image](https://user-images.githubusercontent.com/3318223/93256948-71893e00-f79c-11ea-8075-0a7f84be61ba.png)
```
blu@minopia:~/golang $ go version
go version go1.15.2 linux/arm
blu@minopia:~/golang $ uname -a
Linux minopia.de 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux
blu@minopia:~/golang $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
```
device: raspberry pi 4

**Comment by vishen** [comment]
Thanks! I have cross-compiled it on `linux/armv7` before, but I haven't tried compiling with `go1.15` or on `linux/armv8` yet. I'll take a look!

If possible, are you able to confirm you can use one of the latest releases to run `go-chromecast`? I just want to verify if it is the compiling or the runtime that is failing.

**Comment by Bluscream** [comment]
1.15 is the latest release i could find according to https://www.e-tinkers.com/2019/06/better-way-to-install-golang-go-on-raspberry-pi/

**Comment by vishen** [comment]
That is a crazy long time. I am able to cross-compile successfully with `go-chromecast` successfully to armv8 with: `GOOS=linux GOARCH=arm64 go1.15 build -o go-chromecast`. I don't have a raspberry pi easily to test but I will push out a new release that builds for `linux-armv{7,8}` and hopefully you can use that rather than needing to `go get` since it looks like it may be an issue with Go itself.

**Comment by vishen** [comment]
I have added some arm releases to the latest release https://github.com/vishen/go-chromecast/releases/tag/v0.2.5. Specifically https://github.com/vishen/go-chromecast/releases/download/v0.2.5/go-chromecast_0.2.5_linux_arm64.tar.gz should be for `armv8`
